name: LaTeX to PDF

on:
  push:
    paths: main.tex

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Build docker image
        uses: jumpe1/test8/.github/actions/latex@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: 'Asia/Tokyo'
